const ACTION_TYPES = {
    CREATE_SUPERHERO_CARD_REQUEST: 'CREATE_ADVERTISEMENT_REQUEST',
    CREATE_SUPERHERO_CARD_SUCCESS: 'CREATE_SUPERHERO_CARD_SUCCESS',
    CREATE_SUPERHERO_CARD_ERROR: 'CREATE_SUPERHERO_CARD_ERROR',
    GET_CARDS_REQUEST: 'GET_CARDS_REQUEST',
    GET_CARDS_SUCCESS: 'GET_CARDS_SUCCESS',
    GET_CARDS_ERROR: 'GET_CARDS_ERROR',
    UPDATE_CARD_BY_ID_REQUEST: 'UPDATE_CARD_BY_ID_REQUEST',
    UPDATE_CARD_BY_ID_SUCCESS: 'UPDATE_CARD_BY_ID_SUCCESS',
    UPDATE_CARD_BY_ID_ERROR: 'UPDATE_CARD_BY_ID_ERROR',
    GET_CARD_BY_ID_REQUEST: 'GET_CARD_BY_ID_REQUEST',
    GET_CARD_BY_ID_SUCCESS: 'GET_CARD_BY_ID_SUCCESS',
    GET_CARD_BY_ID_ERROR: 'GET_CARD_BY_ID_ERROR',
    CLEAR_ERROR: 'CLEAR_ERROR'
};

export default ACTION_TYPES;